name: 错误报告
description: 哪里出现了什么问题？
labels: 错误
body:
  - type: checkboxes
    attributes:
      label: 请先确认：
      description: 请确认您已按照以下步骤操作
      options:
        - label: 我尝试附加 `--force` 后重新运行了终端的代码。
          required: false
        - label: 我尝试运行 `brew update-reset` 和 `brew update` 后重新运行了终端的代码。
          required: false
        - label: 我尝试运行 `brew doctor` 并依照提示执行修复指令后重新运行了终端的代码。
          required: false
  - type: textarea
    attributes:
      label: 描述一下错误
    validations:
      required: true
  - type: input
    attributes:
      label: 发生错误前你运行了什么
    validations:
      required: true
  - type: textarea
    attributes:
      label: 携带参数 `--verbose --debug` 再次运行，以获取详细输出内容
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: 运行 `brew doctor` 和 `brew config` 的输出内容
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: 运行 `brew tap` 的输出内容
      render: shell
    validations:
      required: true
