name: Bump casks

inputs:
  HOMEBREW_GITHUB_API_TOKEN:
    description: 'Homebrew GitHub API Token'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Bump outdated casks
      # continue-on-error: true
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ inputs.HOMEBREW_GITHUB_API_TOKEN }}
      shell: bash
      run: |
        parallel -j0 --group --halt now,fail=1 \
          './.github/actions/bump-casks/script.sh {}' \
          ::: $(ls $(brew --repository brewforge/chinese)/Casks/*.rb | xargs -I {} basename {} .rb)
