name: bump

on:
  # pull_request:
  #   branches: [main]
  # push:
  #   branches: [fix-*]
  schedule:
    # Every 12 hours
    # - cron: "20 */12 * * *"
    # Every day at 6am
    - cron: "0 6 * * *"
  # allow run manually
  workflow_dispatch:

permissions: write-all

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_RELOCATABLE_INSTALL_NAMES: 1

jobs:
  bump-casks:
    name: Bump casks
    if: github.repository == 'brewforge/homebrew-chinese'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Brew Tap
        uses: ./.github/actions/brew-tap

      - name: Git Cred
        uses: ./.github/actions/git-cred
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Bump
        env:
          HOMEBREW_DEVELOPER: "1"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        shell: bash -ieo pipefail {0}
        run: |
          rsync -lrv --exclude=.git "$(pwd)" "$(brew --repository brewforge/chinese)"
          cd "$(brew --repository brewforge/chinese)"
          ./.github/actions/bump-casks/script.sh

  bump-formulae:
    name: Bump formulae
    if: github.repository == 'brewforge/homebrew-chinese'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Brew Tap
        uses: ./.github/actions/brew-tap

      - name: Git Cred
        uses: ./.github/actions/git-cred
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Bump
        env:
          HOMEBREW_DEVELOPER: "1"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        shell: bash -ieo pipefail {0}
        run: |
          rsync -lrv --exclude=.git "$(pwd)" "$(brew --repository brewforge/chinese)"
          cd "$(brew --repository brewforge/chinese)"
          ./.github/actions/bump-formulae/script.sh

  bump-formulae-linux:
    name: Bump formulae (Linuxbrew)
    if: github.repository == 'brewforge/homebrew-chinese'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Brew Tap
        uses: ./.github/actions/brew-tap

      - name: Git Cred
        uses: ./.github/actions/git-cred
        with:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Bump
        env:
          HOMEBREW_DEVELOPER: "1"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        shell: bash -ieo pipefail {0}
        run: |
          rsync -lrv --exclude=.git "$(pwd)" "$(brew --repository brewforge/chinese)"
          cd "$(brew --repository brewforge/chinese)"
          ./.github/actions/bump-formulae/script.sh
